### ISSUE TITLE
Separate language server

### ISSUE THREAD

**Issue by IsotoxalDev** [oparaskos/vscode-fountain#30]
Can you separate the language server from the extension so it can be utilized by other test editors which support lsp Eg: Vim, Helix, Kakoune, Lapce etc

**Comment by oparaskos** [comment]
I'll add it to my list 👍🏼

**Comment by oparaskos** [comment]
I've seperated the language server out (linked to this repo as a git submodule for now) here: https://github.com/oparaskos/fountain-lsp-server. 

I've not tested it but you should be able to run the server with other editors by building it and then configuring them to run `node dist/main.js [some options]`.

vscode handles alot of this stuff inside its libraries, but i think the client for vscode runs it with `node dist/main.js --node-ipc --nolazy --inspect=6009 --clientProcessId=?`

**Comment by IsotoxalDev** [comment]
Thank you very much @oparaskos !!
