### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by doinby** [oparaskos/vscode-fountain#31]
### Description
An error message shows when try to use dropdown menu on `.fountain` file

### Device
- Apple M1 Pro
- 16GB RAM
- Mac OS Sonoma 14.0
- VS Code Version: 1.84.2

### Error Message
```
[Error - 12:45:35 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read properties of undefined (reading 'codeLocation')
  Code: -32603 
```
![Screenshot 2023-11-17 at 12 49 23](https://github.com/oparaskos/vscode-fountain/assets/36951678/e78ef540-3ba8-459e-b2af-e00cecc7cba9)

**Comment by oparaskos** [comment]
Thanks, I'll take a look at this 😄

**Comment by oparaskos** [comment]
@doinby I've pushed a new version which I think fixes this issue, could you give it another go and let me know if it's resolved please.
